### PR TITLE
Multiline functions

### PR DESCRIPTION
**Pull request by nikifkon**
Hello,
I didn't find any contribution guides and I'm unfamiliar with a code base.
But with @cser we implement some new features from https://gist.github.com/cser/dabe6e064915701be3d3bb5f50db4d42 and fix some bugs.

Are there any changes left that must be done: docs, web version?

### CODE REVIEW

**Comment by Proektsoftbg** [comment]
Thank you! Great Job!

However, before mreging, I will have to review it. I am also working on the code, we will have to coordinate. On the first glance, I think you have pretty good understanding of the code and what and where to change. 

Currently, the project is not quite ready for contribution. Besides guidelines, we will have to develop unit tests, etc. But I am so happy that we are starting to have such a dedicated community.

**Comment by cser** [comment]
Unfortunately, this is an isolated event. It is unlikely that I will support the project regularly. Just this feature is very necessary.
So, it's too early to worry about the problems of collective development :(. But, unit tests is very good for interpretator developing anyway :)

**Comment by cser** [comment]
@Proektsoftbg:
Hello, Ned!
I rewrite https://gist.github.com/cser/dabe6e064915701be3d3bb5f50db4d42, now it explain this pull request functional.

nikifkon has committed all the functionality and bug fixes that I asked for. That's all. I started using the new version (the latest one, so it turned out, lies here https://github.com/nikifkon/Calcpad/releases/tag/v5 .8.4) and I wait for merging...

**Comment by Proektsoftbg** [comment]
Hi, thank you!

I startet reviewing the changes. Since I have also started working on this (as I mentioned a few weeks ago) it will be difficult to automatically merge both versions. There are also some things that need to be coordinated. It was even better to do that in advance. What I can see at first is:

1. ExpressionParser.cs, line 242: keyword == Keywords.Hide && condition.IsSatisfied etc. All these preprocessor switches must come before any program flow like conditions and loops. They affect the html content in both input and output stages. Since, in input stage the code is not evaluated, it is not possible to depend on conditions. Also, this is not needed as long as you simply nest the corresponding couples of #hide-#show or #val-#equ inside the same condition block.
2. Dots in variable names are reserved for vectors and arrays when they come in turn, like in MathCAD, say `a.1, a.n, a.(2*n+1)`, etc. 
3. Both macros and includes have to be preprocessed as an additional step before we call ExpressionParser.Parse(...). This can be implemented by a simple rewiriting engine that does nothing but replacing the macro calls with the respective strings. After composing the final code, it can be passed to the expression parser. This approach is more clear and easy to implement without affecting the current logic.
4. Macros and includes will disturb some existing features like input fields and line numbers. A multiline macro or included file can contain input fields. We need to think about how to preserve their values.
5. Some of these features I have already implemented on my side.

So, it will be difficult to merge the changes automatically. For me, it will be easier to do that manually and take only what I need. I know that you are not using Html forms and some other existing featres, but they are essential for Calcpad and we cannot afford to break them.

**Comment by cser** [comment]
# 1. `#hide`/`#show`

> ExpressionParser.cs, line 242: keyword == Keywords.Hide && condition.IsSatisfied etc. All these preprocessor switches must come before any program flow like conditions and loops. They affect the html content in both input and output stages. Since, in input stage the code is not evaluated, it is not possible to depend on conditions

OK, I agree - input fields can't be broken

> Also, this is not needed as long as you simply nest the corresponding couples of #hide-#show or #val-#equ inside the same condition block.

OK, I agree that we can't touch `#hide`/`#val` behaviour, but this quote isn't true for `#hide`, for example:

```nginx
#def TRY$()
    out = a^2
    'There out: 'out
#end def
#hide
a = 10
TRY$()' - it is need to hide it
#if out > 20
  a = 2
#end if
#show
TRY$()' - it is need to show it
```

**What to do?** - nothing now, but later - it's need to introduce additional dynamic nested keyword/function for hide, that don't do anything with input fields (additional keyword for show isn't needed)

Variant 1 - one-line function $Hide:
```nginx
#def TRY$()
    out = a^2
    'There out: 'out
#end def
#hide
a = 10
$Hide{TRY$()}
#if out > 20
	a = 2
#end if
#show
TRY$()
```

Variant 2 - '#dynhide' keyword:
```nginx
#def TRY$()
    out = a^2
    'There out: 'out
#end def
#dynhide
	a = 10
	TRY$()
	#if out > 20
	  a = 2
	#end if
##end dynhide
TRY$()
```
# 2. Dots
 
> Dots in variable names are reserved for vectors and arrays when they come in turn, like in MathCAD, say a.1, a.n, a.(2*n+1), etc.

OK, now it's clear why they isn't documented

# 3. Preprocessing

> Both macros and includes have to be preprocessed as an additional step before we call ExpressionParser.Parse(...). This can be implemented by a simple rewiriting engine that does nothing but replacing the macro calls with the respective strings. After composing the final code, it can be passed to the expression parser. This approach is more clear and easy to implement without affecting the current logic.

Are you want to remove all dynamic from macros?
Goodbye conditional macro definition inside `#if`, hello `#if` in several places!
But, OK.

# 4. Input fields and line numbers

> Macros and includes will disturb some existing features like input fields and line numbers. A multiline macro or included file can contain input fields. We need to think about how to preserve their values.

Offtopic:
In my deep opinion input fields should be dynamic, depend on `#if`/`#repeat`/`#def` and appear/disappear on the fly when entering values. Code of Unity3d editors and react.js works so.
The values must be stored by an explicit key (`x=??x`, `x=??x{i}` - for loop, `x=??x{unique_argument}` - for macro). Otherwise, problems will continue to appear.

Essentially:
If input fields ignore `#if` and `#repeat` - let's they ignore `#def`. What can we do else?
In pull request line with error shows inside macros. It's need to show call stack, but one line is normal now.
Where to scroll when clicking on a line inside a macro? - It's better to go nowhere than confuse users

# 5.
 
> Some of these features I have already implemented on my side.

Clear, still waiting :)

**Comment by Proektsoftbg** [comment]
In your example, the first `TRY$()' - it is need to hide it` will hide and `TRY$()' - it is need to show it` will show in the way you wrote it. There is nothing specal about that.
To hide a single line, you can write a helper, using Html comment, e.g.:
```
#def HIDE$(S$)
    '<!--'S$'-->
#end def
```
or
```
#def HIDE$(S$)
   #hide
   S$
   #show
#end def
```
I also thought about changing the way input values are stored. `x = ?{2}` is definitely a simple good way.
If a macro or #include contain input fields, w can add default values on the same line as a list:
#include filename #{2; 3; 4}' - inlude file with three input fileds and set defaults.
or
SELECT_SECTION$() #{2; 3; 4}' - call macro with three input fileds and set defaults.

About conditional macro definitions, you can easilly avoid that. You can define two macros with different names and conditionally call them.

About making input fields dependant on #if-#else-#end if, we can possibly do that in future. This will require dynamic recalculation each time when an input value is changed. This is compilcated and not possible in the current implementtion of the web version. For now, I prefer to use #pre- #post. This is static, but simpler. If we start doing too much changes at once, we will not finish until the end of the year. :)

Lets do it step by step. If you are ahead in your version, you can keep using these features until I manage to catch up. However, I want to keep Calcpad as simple as possible. This is the charm of it. :) You are always trying to make things more complicated than necessary. ;) I am sure that when I get the final implemenation, and you try it, you will see that you can do all the things you need, but in simpler way.

The preprocessing of includes and macros will bring us one great feature: you will be able to see the final "unwarped" source code after all includes and macros are rewriten with their contents. It will be very good for testing your worksheets and keep track of what you are doing.

**Comment by cser** [comment]
> To hide a single line, you can write a helper, using Html comment, e.g.:
Ha! Realy, it's possible with static macro :)

**Comment by cser** [comment]
> I also thought about changing the way input values are stored. x = ?{2} is definitely a simple good way.
> If a macro or #include contain input fields, w can add default values on the same line as a list:
> #include filename #{2; 3; 4}' - inlude file with three input fileds and set defaults.
> or
> SELECT_SECTION$() #{2; 3; 4}' - call macro with three input fileds and set defaults.

There are no ideas on the above O_o

> About conditional macro definitions, you can easilly avoid that. You can define two macros with different names and conditionally call them.

It's like in C# - missing virtual methods makes condition count groving in other places.
Anyway, let's give this up for simplification and nice testing

> About making input fields dependant on #if-#else-#end if, we can possibly do that in future. This will require dynamic recalculation each time when an input value is changed. This is compilcated and not possible in the current implementtion of the web version. For now, I prefer to use #pre- #post. This is static, but simpler. If we start doing too much changes at once, we will not finish until the end of the year. :)

Well, we'll have to work with what we have

> Lets do it step by step. If you are ahead in your version, you can keep using these features until I manage to catch up. However, I want to keep Calcpad as simple as possible. This is the charm of it. :) You are always trying to make things more complicated than necessary. ;) I am sure that when I get the final implemenation, and you try it, you will see that you can do all the things you need, but in simpler way.

:)

> The preprocessing of includes and macros will bring us one great feature: you will be able to see the final "unwarped" source code after all includes and macros are rewriten with their contents. It will be very good for testing your worksheets and keep track of what you are doing.

That's right

**Pull request closed without merging**
